[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  
[[redirects]]
  from = "/*"
  to = "https://makeholdinggreatagain.com/:splat"
  status = 301
  force = true
